### PR TITLE
Add formating

### PR DESCRIPTION
**Pull request by triptec**
Add the possibility to format personnummer for comparisons, both short(640327-3813, 130401+2931) and long (196403273813, 191304012931)

### CODE REVIEW

**Comment by frozzare** [comment]
Looks good, but I think we should follow the php package in this case instead of `format_long` and `format_short`. Maybe not the best solution but it's better to do the same way in all packages :) 

```php
// Short format (YYMMDD-XXXX)
Personnummer::format(6403273813);
//=> 640327-3813

// Long format (YYYYMMDDXXXX)
Personnummer::format('6403273813', true);
//=> 196403273813
```

**Comment by triptec** [comment]
Sounds like a good idea! I'll have a look at that and also perhaps look at how the php implementation derive separator and century

**Comment by frozzare** [comment]
We have added a spec about how the personnummer package should work, format is a part of version 2. 

https://github.com/personnummer/meta

**Comment by frozzare** [comment]
Closing, feature is merged in another PR #12

**Pull request closed without merging**
