### PR TITLE
Add get_age function

### LINKED ISSUE #8: Add get age
See package spec https://github.com/personnummer/meta

### PR DESCRIPTION
**Pull request by dannyhajj**
Closes #8 
- Added the `get_age` function that takes a Swedish SSN as a required parameter and a second optional boolean parameter named `include_coordination_number` (defaults to `True`).
- Included the `mock` library as a dependency for tests in order to mock the current date which is needed for testing the `get_age` function
- Re-introduced tests for the format function when passing invalid inputs. I used the ones that were kept in the `test_wrong_personnummer_or_types` function in the [111bbde](https://github.com/personnummer/python/commit/111bbde78344cfc1b4fe8517251bc713d9fbdc54) commit.
- For testing the `get_age` function, I used the same values used in the PHP library.

If some values should be omitted or changed in the tests according to #14, let me know which ones. I wouldn't mind updating the PR.

_I strongly recommend documenting the values that need to be tested in the Meta package since this appears to be an issue._

### CODE REVIEW

**Comment by dannyhajj** [comment]
@frozzare Can you check this? I'd like to have the Python package updated so I can use the `format` function.
Let me know if you need anything changed.

**Comment by frozzare** [comment]
Looks good! Haven't had time to look at this yet. Will try to push out a new version as soon as I can.

**Comment by frozzare** [comment]
@dannyhajj  Released! Sorry for the delay :)

**Comment by dannyhajj** [comment]
@frozzare Awesome! No need to be sorry lol.

I suggest updating the [release note](https://github.com/personnummer/python/releases/tag/v1.1.0) and include the following since the `format` function wasn't available before this release.
> - Added `format`

Maybe even use `v2.0.0` instead of `v1.0.0` since it follows the v2 spec now. Sorry for nitpicking lol.

**Comment by frozzare** [comment]
Great, updated the release note.

We're working on a v3 spec and then we will update all packages to v3, so will let the v1.1 be right now. It dosen't have to match the spec vers. Will update meta readme and website with new python version.

**Pull request merged**
